version: '3.7'

services:
  mariadb:
    image: mariadb
    container_name: wp4-mysql
    networks:
      nginx_net:
    restart: always
    ports:
      - "3304:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123Qwe123
      MYSQL_DATABASE: wp4
      MYSQL_USER: wp4
      MYSQL_PASSWORD: 123Qwe123

  php:
    build: ./images/php
    container_name: wp4-php
    networks:
      nginx_net:
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_HOST: wp4-mysql
      DB_PASS: 123Qwe123
      DB_NAME: wp4
      DB_USER: wp4
    links:
      - mariadb
    volumes:
      - ./www:/var/www

  nginx:
    image: nginx
    container_name: wp4-nginx
    networks:
      nginx_net:
    restart: always
    ports:
      - "84:80"
      - "444:443"
    depends_on:
      - mariadb
      - php
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - ./cert:/etc/nginx/ssl
#    environment:
#      - VIRTUAL_HOST=wp4.loc
#      - LETSENCRYPT_HOST=wp4.loc
#      - LETSENCRYPT_EMAIL=admin@wp4.loc
    links:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp4-pma
    networks:
      nginx_net:
    restart: always
    ports:
      - "8084:80"
    links:
      - mariadb:mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123Qwe123
      PMA_HOST: mariadb


networks:
  nginx_net:
    external: true
